---
settings:
  name: How to enable StorageGRID in your environment
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Cómo habilitar StorageGRID
    url: "/index.html"
  - section: third-party
  - section: product-feature-guides
  - section: tools-apps-guides
  - section: examples
  - title: Publicaciones de blog
    url: "/blogs.html"
  - title: Documentación de StorageGRID
    url: "/storagegrid-documentation.html"
