---
settings:
  name: StorageGRID solutions and resources
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: true
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Soluciones y recursos de StorageGRID
    url: "/index.html"
  - title: Pruebe StorageGRID
    url: "/evaluation-software.html"
  - section: third-party
  - section: product-feature-guides
  - section: tools-apps-guides
  - section: examples
  - section: technical-reports
  - title: Pruebe StorageGRID
    url: "/evaluation-software.html"
  - title: Publicaciones de blog
    url: "/blogs.html"
  - title: Documentación de StorageGRID
    url: "/storagegrid-documentation.html"
  - title: Avisos legales
    url: "/legal-notices.html"
