---
permalink: technical-reports/monitor/alerts-monitoring.html 
sidebar: sidebar 
keywords: alerts, storagegrid 
summary: Aprenda a utilizar el sistema de alertas en StorageGRID para supervisar problemas, gestionar alertas personalizadas y extender las notificaciones de alertas a través de SNMP o correo electrónico. 
---
= Utilice alertas para supervisar StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
Aprenda a usar el sistema de alertas en StorageGRID para supervisar problemas, gestionar alertas personalizadas y ampliar las notificaciones de alertas con SNMP o correo electrónico.

Las alertas proporcionan información crítica que le permite supervisar los diversos eventos y condiciones del sistema StorageGRID.

El sistema de alertas está diseñado para ser la herramienta principal para supervisar cualquier problema que se pueda producir en el sistema StorageGRID. El sistema de alertas se centra en problemas prácticos en el sistema y ofrece una interfaz fácil de usar.

Proporcionamos una variedad de reglas de alerta predeterminadas que tienen como objetivo ayudar a supervisar y solucionar problemas de su sistema. Para gestionar aún más las alertas, puede editar o deshabilitar alertas predeterminadas y silenciar las notificaciones de alertas.

Las alertas también se pueden ampliar mediante SNMP o notificaciones por correo electrónico.

Para obtener más información sobre las alertas, consulte el documento https://docs.netapp.com/us-en/storagegrid-118/monitor/managing-alerts-and-alarms.html["documentación de productos"^] disponible en línea y en formato PDF.
