---
permalink: technical-reports/monitor/audit-log-monitoring.html 
sidebar: sidebar 
keywords: audit logs, storagegrid 
summary: Descubra cómo usar el registro de auditoría de StorageGRID para obtener información detallada sobre la actividad de inquilinos y el grid, y cómo aprovechar herramientas como Splunk para análisis de registros. 
---
= Utilice los registros de auditoría para supervisar StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
Aprenda a usar el registro de auditoría de StorageGRID para obtener información detallada sobre la actividad de inquilino y grid, y cómo aprovechar herramientas como Splunk para análisis de registros.

El registro de auditoría de StorageGRID permite recopilar información detallada sobre la actividad del inquilino y el grid. El registro de auditoría puede exponerse para análisis mediante NFS. Para obtener instrucciones detalladas sobre cómo exportar el registro de auditoría, consulte la Guía del administrador de.

Una vez exportada la auditoría, puede usar herramientas de análisis de registro como Splunk o Logstash + Elasticsearch para comprender la actividad de los inquilinos o para crear informes detallados de facturación y pago por uso.

Los detalles sobre los mensajes de auditoría se incluyen en la documentación de StorageGRID. Consulte https://docs.netapp.com/us-en/storagegrid-118/audit/audit-messages-main.html["Auditar mensajes"^].
