---
sidebar: sidebar 
permalink: technical-reports/bare-metal-index.html 
keywords: install, storagegrid, deploy, bare metal 
summary: Aprende a instalar StorageGRID en una cuadrícula bare metal. 
---
= Introducción a la instalación de StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Aprenda a instalar StorageGRID en hosts bare metal.

TR-4882 proporciona un conjunto práctico de instrucciones paso a paso que produce una instalación de funcionamiento de NetApp StorageGRID. La instalación puede estar en configuración básica o en máquinas virtuales que se ejecuten en Red Hat Enterprise Linux (RHEL). El enfoque consiste en realizar una instalación «revisada» de seis servicios contenerizados de StorageGRID en tres máquinas físicas (o virtuales) en una configuración de diseño y almacenamiento sugerida. A algunos clientes es posible que les resulte más fácil comprender el proceso de puesta en marcha siguiendo el ejemplo de puesta en marcha en este TR.

Para obtener información más detallada sobre StorageGRID y el proceso de instalación, consulte https://docs.netapp.com/us-en/storagegrid-118/landing-install-upgrade/index.html[] [Install, upgrade, and hotfix StorageGRID] en la documentación del producto.

Antes de iniciar la puesta en marcha, examinemos los requisitos de computación, almacenamiento y redes del software de NetApp StorageGRID. StorageGRID se ejecuta como un servicio en contenedores dentro de Podman o Docker. En este modelo, algunos requisitos hacen referencia al sistema operativo del host (el sistema operativo que aloja Docker, que ejecuta el software StorageGRID). Además, algunos de los recursos se asignan directamente a los contenedores de Docker que se ejecutan dentro de cada host. En esta implementación, con el fin de maximizar el uso del hardware, estamos implementando dos servicios por host físico. Para obtener más información, continúe en la siguiente sección, link:prerequisites-install-storagegrid.html["Requisitos previos para instalar StorageGRID"].

Los pasos descritos en este TR dan como resultado una instalación de StorageGRID en seis hosts sin configuración básica. Ahora tiene una red de red y cliente que funcionan, lo cual es útil en la mayoría de los escenarios de prueba.



== Dónde encontrar información adicional

Si desea obtener más información sobre la información descrita en este TR, consulte los siguientes recursos de documentación:

* Centro de documentación de NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-118/[]
* Habilitación para NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-enable/[]
* Documentación de producto de NetApp https://www.netapp.com/support-and-training/documentation/[]

