---
sidebar: sidebar 
permalink: technical-reports/data-security-index.html 
keywords: security features, storagegrid 
summary: Descubra las funciones de seguridad integrales de la solución de almacenamiento de objetos de StorageGRID. 
---
= Protege los datos y metadatos de StorageGRID en un almacén de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Descubra las funciones de seguridad integrales de la solución de almacenamiento de objetos de StorageGRID.

Esta es una descripción general de las muchas características de seguridad de NetApp® StorageGRID®, que cubren el acceso a datos, objetos y metadatos, el acceso administrativo y la seguridad de la plataforma. Se ha actualizado para incluir las últimas características lanzadas con StorageGRID 11,9.

La seguridad es una parte integral de la solución de almacenamiento de objetos de NetApp StorageGRID. La seguridad es especialmente importante porque muchos tipos de datos de contenido enriquecido que se adaptan perfectamente al almacenamiento de objetos también son confidenciales por naturaleza y sujetos a regulaciones y cumplimiento de normativas. A medida que las funcionalidades de StorageGRID continúan evolucionando, el software pone a su disposición muchas funciones de seguridad imprescindibles para proteger la política de seguridad de la organización y ayudar a la organización a cumplir las prácticas recomendadas del sector.

Este documento ofrece una descripción general de las muchas características de seguridad de StorageGRID 11,9, divididas en cinco categorías:

* Funciones de seguridad de acceso a los datos
* Funciones de seguridad de objetos y metadatos
* Funciones de seguridad de administración
* Funciones de seguridad de la plataforma
* Integración del cloud


Este documento está diseñado para ser una hoja de datos de seguridad; no detalla cómo configurar el sistema para que admita las características de seguridad enumeradas en que no están configuradas de forma predeterminada. El https://docs.netapp.com/us-en/storagegrid-118/harden/index.html["Guía para el fortalecimiento de StorageGRID"^] está disponible en la página oficial https://docs.netapp.com/us-en/storagegrid-118/["Documentación de StorageGRID"^] .

Además de las capacidades descritas en este informe, StorageGRID sigue el https://www.netapp.com/us/legal/vulnerability-response.aspx["Política de notificación y respuesta de vulnerabilidad de seguridad de los productos de NetApp"^]. Las vulnerabilidades informadas se verifican y responden a ellas según el proceso de respuesta a incidentes de seguridad del producto.

NetApp StorageGRID ofrece funciones de seguridad avanzadas para casos de uso de almacenamiento de objetos empresariales muy exigentes.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* NetApp StorageGRID: Evaluación del cumplimiento de las normas SEC 17a-4(f), FINRA 4511(c) y CFTC 1,31(c)-(d) https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* Página de documentación de StorageGRID 11,9 https://docs.netapp.com/us-en/storagegrid-119/[]
* Documentación de producto de NetApp https://www.netapp.com/support-and-training/documentation/[]




== Términos y acrónimos

En esta sección se proporcionan definiciones de la terminología utilizada en el documento.

[cols="40,60"]
|===
| Término o acrónimo | Definición 


| S3 | Servicio de almacenamiento simple. 


| Cliente | Una aplicación que puede interactuar con StorageGRID mediante el protocolo S3 para el acceso a los datos o el protocolo HTTP para la gestión. 


| Administrador de inquilinos | El administrador de la cuenta de inquilino de StorageGRID 


| Usuario inquilino | Un usuario dentro de una cuenta de inquilino de StorageGRID 


| TLS | Seguridad de la capa de transporte 


| ILM | Gestión del ciclo de vida de la información 


| LAN | Red de área local 


| Administrador de grid | El administrador del sistema StorageGRID 


| Cuadrícula | El sistema StorageGRID 


| Cucharón | Un contenedor para objetos almacenados en S3 


| LDAP | Protocolo ligero de acceso a directorios 


| SEG | Securities and Exchange Commission; regula los miembros, agentes y distribuidores de las operaciones 


| FINRA | Autoridad reguladora de la industria financiera; aplaza los requisitos de formato y medios de la norma SEC 17a-4(f) 


| CFTC | Commodity Futures Trading Comissions; regula el comercio de futuros de materias primas 


| NIST | Instituto Nacional de Estándares y Tecnología 
|===