---
sidebar: sidebar 
permalink: technical-reports/ransomware-protection-index.html 
keywords: ransomware attacks, storagegrid, best practices 
summary: Obtén más información sobre los ataques de ransomware y cómo proteger los datos con las prácticas recomendadas de seguridad de StorageGRID. 
---
= Protege objetos de StorageGRID S3 contra el ransomware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Obtén más información sobre los ataques de ransomware y cómo proteger los datos con las prácticas recomendadas de seguridad de StorageGRID.

Los ataques de ransomware están en auge. Este documento proporciona algunas recomendaciones sobre cómo proteger los datos de objetos en StorageGRID.

Hoy en día, el ransomware es el peligro siempre presente en los centros de datos. El ransomware está diseñado para cifrar datos y dejarlos inutilizables por los usuarios y las aplicaciones que dependen de ellos. La protección comienza con las defensas habituales de las redes reforzadas y las prácticas de seguridad de usuario sólidas, y tenemos que seguir con las prácticas de seguridad de acceso a los datos.

El ransomware es una de las mayores amenazas de seguridad de hoy en día. El equipo de NetApp StorageGRID está trabajando con nuestros clientes para mantenerse a la cabeza de estas amenazas. Con el uso de bloqueo de objetos y control de versiones, puede protegerse frente a alteraciones no deseadas y recuperarse de ataques maliciosos. La seguridad de datos es una aventura de múltiples capas, donde tu almacenamiento de objetos es solo una parte del centro de datos.



== Mejores prácticas de StorageGRID

Para StorageGRID, las prácticas recomendadas de seguridad deben incluir el uso de HTTPS con certificados firmados tanto para la gestión como para el acceso a los objetos. Cree cuentas de usuario dedicadas para aplicaciones e individuos, y no utilice las cuentas raíz de inquilino para el acceso a aplicaciones o el acceso a los datos de usuario. En otras palabras, siga el principio de privilegio mínimo. Utilice grupos de seguridad con directivas de gestión de acceso e identidad definidas (IAM) para controlar los derechos de usuario y acceder a cuentas específicas de las aplicaciones y los usuarios. Con estas medidas, aún debe asegurarse de que los datos estén protegidos. En el caso de Simple Storage Service (S3), cuando se modifican objetos para cifrarlos, se realiza mediante una sobrescritura del objeto original.



== Métodos de defensa

El principal mecanismo de protección contra ransomware en la API S3 es implementar el bloqueo de objetos. No todas las aplicaciones son compatibles con el bloqueo de objetos, por lo que hay otras dos opciones para proteger los objetos que se describen en este informe: Replicación a otro depósito con control de versiones activado y control de versiones con políticas de IAM.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Centro de documentación de NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-118/[]
* Habilitación para NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-enable/[]
* Documentación de producto de NetApp https://www.netapp.com/support-and-training/documentation/[]

