---
sidebar: sidebar 
permalink: technical-reports/bare-metal/node-config-file-storagegrid.html 
keywords: node config, storagegrid 
summary: Comprenda cómo preparar los archivos de configuración de nodos para StorageGRID. 
---
= Prepare los archivos de configuración de nodos para StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Aprenda a preparar los archivos de configuración de nodos para StorageGRID.

En líneas generales, el proceso de configuración de nodos incluye los siguientes pasos:

.Pasos
. Cree el `/etc/storagegrid/nodes` directorio en todos los hosts.
+
[listing]
----
sudo [root@host1 ~]# mkdir -p /etc/storagegrid/nodes
----
. Cree los archivos necesarios por host físico para que coincidan con la distribución de tipo de contenedor/nodo. En este ejemplo, creamos dos archivos por host físico en cada máquina host.
+

NOTE: El nombre del archivo define el nombre de nodo real para la instalación. Por ejemplo, `dc1-adm1.conf` se convierte en un nodo llamado `dc1-adm1`.

+
-- Host1:
`dc1-adm1.conf`
`dc1-sn1.conf`

+
-- Host2:
`dc1-gw1.conf`
`dc1-sn2.conf`

+
-- host3:
`dc1-gw2.conf`
`dc1-sn3.conf`





== Preparando los archivos de configuración del nodo

Los siguientes ejemplos utilizan el `/dev/disk/by-path` formato. Puede verificar las rutas correctas ejecutando los siguientes comandos:

[listing]
----
[root@host1 ~]# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda 8:0 0 90G 0 disk
├─sda1 8:1 0 1G 0 part /boot
└─sda2 8:2 0 89G 0 part
├─rhel-root 253:0 0 50G 0 lvm /
├─rhel-swap 253:1 0 9G 0 lvm
└─rhel-home 253:2 0 30G 0 lvm /home
sdb 8:16 0 200G 0 disk /var/lib/docker
sdc 8:32 0 90G 0 disk
sdd 8:48 0 200G 0 disk
sde 8:64 0 200G 0 disk
sdf 8:80 0 4T 0 disk
sdg 8:96 0 4T 0 disk
sdh 8:112 0 4T 0 disk
sdi 8:128 0 90G 0 disk
sr0 11:0 1 1024M 0 rom
----
Y estos comandos:

[listing]
----
[root@host1 ~]# ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:02:01.0-ata-1.0 -> ../../sr0
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:4:0 -> ../../sde
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:5:0 -> ../../sdf
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:6:0 -> ../../sdg
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:8:0 -> ../../sdh
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:9:0 -> ../../sdi
----


== Ejemplo de nodo de administración principal

Nombre de archivo de ejemplo:

[listing]
----
/etc/storagegrid/nodes/dc1-adm1.conf
----
Contenido del archivo de ejemplo:


NOTE: Las rutas de acceso a los discos pueden seguir los siguientes ejemplos o `/dev/mapper/alias` utilizar la nomenclatura de estilos. No utilice nombres de dispositivos de bloqueo, `/dev/sdb` como porque pueden cambiar al reiniciar y causar grandes daños a la red.

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
MAXIMUM_RAM = 24g
BLOCK_DEVICE_VAR_LOCAL = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
BLOCK_DEVICE_AUDIT_LOGS = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
BLOCK_DEVICE_TABLES = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:4:0
GRID_NETWORK_TARGET = ens192
CLIENT_NETWORK_TARGET = ens224
GRID_NETWORK_IP = 10.193.204.43
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.193.204.1
CLIENT_NETWORK_CONFIG = STATIC
CLIENT_NETWORK_IP = 10.193.205.43
CLIENT_NETWORK_MASK = 255.255.255.0
CLIENT_NETWORK_GATEWAY = 10.193.205.1
----


== Ejemplo de un nodo de almacenamiento

Nombre de archivo de ejemplo:

[listing]
----
/etc/storagegrid/nodes/dc1-sn1.conf
----
Contenido del archivo de ejemplo:

[listing]
----
NODE_TYPE = VM_Storage_Node
MAXIMUM_RAM = 24g
ADMIN_IP = 10.193.174.43
BLOCK_DEVICE_VAR_LOCAL = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:9:0
BLOCK_DEVICE_RANGEDB_00 = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:5:0
BLOCK_DEVICE_RANGEDB_01 = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:6:0
BLOCK_DEVICE_RANGEDB_02 = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:8:0
GRID_NETWORK_TARGET = ens192
CLIENT_NETWORK_TARGET = ens224
GRID_NETWORK_IP = 10.193.204.44
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.193.204.1
----


== Ejemplo de nodo de pasarela

Nombre de archivo de ejemplo:

[listing]
----
/etc/storagegrid/nodes/dc1-gw1.conf
----
Contenido del archivo de ejemplo:

[listing]
----
NODE_TYPE = VM_API_Gateway
MAXIMUM_RAM = 24g
ADMIN_IP = 10.193.204.43
BLOCK_DEVICE_VAR_LOCAL = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
GRID_NETWORK_TARGET = ens192
CLIENT_NETWORK_TARGET = ens224
GRID_NETWORK_IP = 10.193.204.47
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.193.204.1
CLIENT_NETWORK_IP = 10.193.205.47
CLIENT_NETWORK_MASK = 255.255.255.0
CLIENT_NETWORK_GATEWAY = 10.193.205.1
----