---
sidebar: sidebar 
permalink: technical-reports/commvault/s3-consistency-levels.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Explora pocos casos prácticos de las configuraciones de StorageGRID implementadas por los clientes y EL DEPARTAMENTO DE TI de NetApp. 
---
= Recomendación de nivel de coherencia del bloque
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
NetApp StorageGRID permite al usuario final seleccionar el nivel de coherencia de las operaciones realizadas en los objetos en bloques de Simple Storage Service (S3).

CommVault MediaAgent son transportadores de datos en un entorno Commvault. En la mayoría de los casos, los MediaAgent están configurados para escribir localmente en un sitio StorageGRID principal. Por esta razón, se recomienda un alto nivel de consistencia dentro de un sitio primario local. Use las siguientes directrices cuando defina el nivel de coherencia en los buckets Commvault creados en StorageGRID.

[NOTE]
====
Si tiene una versión de CommVault anterior a la 11.0.0 - Service Pack 16, considere la posibilidad de actualizar CommVault a la versión más reciente. Si eso no es una opción, asegúrese de seguir las pautas para su versión.

====
* Versiones de CommVault anteriores a 11.0.0 - Service Pack 16.* En versiones anteriores a 11.0.0 - Service Pack 16, CommVault realiza operaciones S3 HEAD y GET en objetos no existentes como parte del proceso de restauración y poda. Establece el nivel de coherencia de buckets en sitio fuerte para alcanzar el nivel óptimo de coherencia para los backups de Commvault en StorageGRID.
* CommVault versiones 11.0.0 - Service Pack 16 y posteriores.* En las versiones 11.0.0 - Service Pack 16 y posteriores, se minimiza el número de operaciones S3 HEAD y GET realizadas en objetos no existentes. Establezca el nivel de coherencia de bloques predeterminado en Read-after-new-write para garantizar un nivel de coherencia alto en el entorno Commvault y StorageGRID.

